### ISSUE TITLE
Windows Npm install & Run dev Errors

### ISSUE THREAD

**Issue by serkandyck** [ezekielchentnik/preact-pwa#11]
Hey, shrink-ray get tons of error about node-pre-gyp and node-zopfli with c++ compiler and python after this i follow installation guide for shrink-ray and succesfull installed. but now i started project with yarn dev or npm run dev command look everything ok but, if i try localhost:8080 console show this error
--------------------------------------------------
Error: Promises not resolved after 100 ms
    at Timeout._onTimeout (C:\Users\EKK\Desktop\test\src\app\utils\withTimeout.js:4:14)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by serkandyck** [comment]
Problem Solved İf u follow node-pre-gyp İnstallation document on windows succes install
